services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: expensify
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # ✅ this is fine
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .  # ← FIXED: now Docker Compose can find your Dockerfile + JAR
    container_name: expensify-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/expensify
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
